[package]
name = "geckon-swap-sc-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.geckon-swap-sc]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.31.0"
